[package]
name = "mysql_source"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = { workspace = true }
cds = { workspace = true }
schema = { workspace = true }
serde_json = { workspace = true }
source = { workspace = true }
sqlx = { workspace = true, features = ["mysql"] }
tokio = { workspace = true }
tracing = { workspace = true }
