[package]
name = "engine"
version.workspace = true
edition.workspace = true

[dependencies]
cds = { workspace = true }
schema = { workspace = true }
subscription_index = { workspace = true }
user_state = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
