//! Stable, sorted YAML emission for [`SyncSchema`].

use anyhow::{Context, Result};
use schema::{EntityDef, FieldDef, FieldMode, IdentityDef, SourceDef, SyncSchema};
use serde::Serialize;
use std::collections::BTreeMap;

#[derive(Serialize)]
struct YamlSchema {
    entities: BTreeMap<String, YamlEntity>,
}

#[derive(Serialize)]
struct YamlEntity {
    identity: IdentityDef,
    sources: BTreeMap<String, SourceDef>,
    fields: BTreeMap<String, YamlField>,
}

#[derive(Serialize)]
struct YamlField {
    source: String,
    mode: FieldMode,
    #[serde(skip_serializing_if = "Option::is_none")]
    ordering: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    flush_ms: Option<u64>,
    #[serde(skip_serializing_if = "Option::is_none")]
    column: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    path: Option<String>,
}

impl From<&FieldDef> for YamlField {
    fn from(field: &FieldDef) -> Self {
        Self {
            source: field.source.clone(),
            mode: field.mode,
            ordering: field.ordering.clone(),
            flush_ms: field.flush_ms,
            column: field.column.clone(),
            path: field.path.clone(),
        }
    }
}

impl From<&EntityDef> for YamlEntity {
    fn from(entity: &EntityDef) -> Self {
        let sources: BTreeMap<_, _> = entity
            .sources
            .iter()
            .map(|(k, v)| (k.clone(), v.clone()))
            .collect();
        let fields: BTreeMap<_, _> = entity
            .fields
            .iter()
            .map(|(k, v)| (k.clone(), YamlField::from(v)))
            .collect();
        Self {
            identity: entity.identity.clone(),
            sources,
            fields,
        }
    }
}

/// Serialize a schema with alphabetically sorted entity / source / field keys.
pub fn schema_to_yaml(schema: &SyncSchema) -> Result<String> {
    let entities: BTreeMap<_, _> = schema
        .entities
        .iter()
        .map(|(k, v)| (k.clone(), YamlEntity::from(v)))
        .collect();
    let yaml = YamlSchema { entities };
    let body = serde_yaml::to_string(&yaml).context("serialize schema yaml")?;
    Ok(format!(
        "# Generated by `substate init`. Review before running `substate serve`.\n{body}"
    ))
}

#[cfg(test)]
mod tests {
    use super::*;
    use schema::SyncSchema;

    #[test]
    fn emit_is_sorted_and_round_trips() {
        let schema = SyncSchema::from_yaml_str(
            r#"
entities:
  zebra:
    identity: { field: id }
    sources:
      postgres: { type: postgres, table: zebras }
    fields:
      id: { source: postgres, mode: transactional }
      name: { source: postgres, mode: transactional }
  aardvark:
    identity: { field: id }
    sources:
      postgres: { type: postgres, table: aardvarks }
    fields:
      id: { source: postgres, mode: transactional }
"#,
        )
        .unwrap();
        let yaml = schema_to_yaml(&schema).unwrap();
        let aardvark = yaml.find("aardvark:").unwrap();
        let zebra = yaml.find("zebra:").unwrap();
        assert!(aardvark < zebra, "entities should be sorted: {yaml}");
        SyncSchema::from_yaml_str(&yaml).unwrap();
    }
}
